In [2]:
import os
import json
import numpy as np
from PIL import Image
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer

# Paths to your images and labels
image_folder = 'C:\\Users\\rushi\\Desktop\\3rd year project\\Images'
json_folder = 'C:\\Users\\rushi\\Desktop\\3rd year project\\Labeled Image'

# Fixed size for the images (e.g., 1200x1200 pixels)
fixed_size = (1200, 1200)

# Function to load and preprocess images and labels
def load_images_and_labels(image_folder, json_folder):
    data = []
    labels = []
    image_files = [f for f in os.listdir(image_folder) if f.endswith('.jpg')]
    
    for img_file in image_files:
        # Load and resize the image
        img_path = os.path.join(image_folder, img_file)
        image = Image.open(img_path).convert('L')  # Grayscale
        image = image.resize(fixed_size)
        image_data = np.array(image) / 255.0  # Normalize to [0, 1]
        image_data = 2 * image_data - 1  # Scale to [-1, 1] for Tanh
        
        # Load corresponding JSON label
        json_file = img_file.replace('.jpg', '.json')
        json_path = os.path.join(json_folder, json_file)
        
        if os.path.exists(json_path):
            with open(json_path, 'r') as f:
                label_data = json.load(f)
                labels.append(label_data)  # Append the JSON data as a label
                data.append(image_data)
    
    return np.array(data), labels

# Load images and labels
data, labels = load_images_and_labels(image_folder, json_folder)
print(f"Loaded {len(data)} images and {len(labels)} labels.")


Loaded 24 images and 24 labels.


In [3]:
import os
import json
from sklearn.feature_extraction.text import CountVectorizer

# Define a function to create descriptions based on JSON labels
def create_description(label_data):
    room_types = [shape['label'] for shape in label_data['shapes']]
    room_count = len(set(room_types))
    
    # Basic description based on room types
    if room_count == 1:
        bhk_type = "Studio"
    else:
        bhk_type = f"{room_count}BHK"
    
    description = f"{bhk_type} floor plan with " + ", ".join(set(room_types))
    return description

# Directory containing JSON files
json_folder = 'C:\\Users\\rushi\\Desktop\\3rd year project\\Labeled Image'  # Update this with the path to your folder containing JSON files
descriptions = []

# Iterate over all JSON files in the folder
for filename in os.listdir(json_folder):
    if filename.endswith('.json'):
        json_path = os.path.join(json_folder, filename)
        with open(json_path, 'r') as f:
            label_data = json.load(f)
            description = create_description(label_data)
            descriptions.append(description)

# Vectorize descriptions
vectorizer = CountVectorizer()
text_embeddings = vectorizer.fit_transform(descriptions).toarray()

print("Text Embeddings Shape:", text_embeddings.shape)
print("Sample Text Embeddings:", text_embeddings[:5])  # Print sample embeddings for verification


Text Embeddings Shape: (24, 13)
Sample Text Embeddings: [[0 0 1 0 0 1 1 1 1 1 0 1 1]
 [0 0 1 0 0 1 1 1 1 1 0 1 1]
 [1 0 0 0 1 1 1 0 0 1 0 0 1]
 [0 0 1 0 0 1 1 1 1 1 0 1 1]
 [0 0 1 0 0 1 1 1 1 1 0 1 1]]


In [4]:
print (descriptions)

['4BHK floor plan with kitchen, hall, Toilet, bedroom', '4BHK floor plan with kitchen, hall, Toilet, bedroom', '2BHK floor plan with balcony, bedroom', '4BHK floor plan with kitchen, hall, Toilet, bedroom', '4BHK floor plan with kitchen, hall, Toilet, bedroom', '4BHK floor plan with kitchen, hall, Toilet, bedroom', '5BHK floor plan with hall, balcony, bedroom, kitchen, Toilet', '5BHK floor plan with hall, balcony, bedroom, kitchen, Toilet', '4BHK floor plan with kitchen, hall, Toilet, bedroom', '5BHK floor plan with hall, balcony, bedroom, kitchen, Toilet', '5BHK floor plan with hall, balcony, bedroom, kitchen, Toilet', '4BHK floor plan with kitchen, hall, Toilet, bedroom', '5BHK floor plan with hall, balcony, bedroom, kitchen, Toilet', '4BHK floor plan with kitchen, hall, balcony, bedroom', '5BHK floor plan with hall, balcony, bedroom, kitchen, Toilet', '5BHK floor plan with hall, balcony, bedroom, kitchen, Toilet', '5BHK floor plan with hall, balcony, bedroom, kitchen, Toilet', '4BHK